# Generated by Django 3.0.5 on 2021-07-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210720_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='edit_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
